[package]
name = "tokio-http2"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
rustls = {
  version = "0.23",
  default-features = false,
  features = [
    "aws_lc_rs",
    "std",
    "tls12",
  ]
}
rustls-pki-types = { version = "1.14", features = ["std"] }
rustls-platform-verifier = "0.7"
shiguredo_http2 = { path = "../.." }
tokio = {
  version = "1.52",
  features = [
    "io-util",
    "macros",
    "net",
    "rt",
    "sync",
    "time",
  ]
}
tokio-rustls = "0.26"

[dev-dependencies]
rcgen = "0.14"
shiguredo_nghttp2 = { path = "../shiguredo_nghttp2" }
tokio = { version = "1.52", features = ["full"] }
tokio-nghttp2 = { path = "../tokio-nghttp2" }
